### ISSUE TITLE
How to set / check expiration? Also example typo

### ISSUE THREAD

**Issue by erichonkanen** [achambers/ember-cli-cookie#11]
Hello,

Your example got `.get()` is missing a `token =` I think on line `this.cookie.get('my-key');`

Also, how can I pass in an expiration date / time and check it? Is that just e.g. `this.cookie.set('foo', 'bar', {expires: 1})`?

**Comment by erichonkanen** [comment]
also what is the proper way to install this with initializer/instance-initializers from the newer ember versions? Im setting a cookie but when I do a page refresh it seems to be lost!

**Comment by alvinvogelzang** [comment]
@erichonkanen you can use `this.cookie.set('foo', 'bar', { expires: 1 })`

As you can see in [ember-cli-cookie/bower.json](https://github.com/achambers/ember-cli-cookie/blob/master/bower.jso)n this addon is just using the jquery-cookie plugin

**Comment by erichonkanen** [comment]
thanks!
